# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Builder
on:
  workflow_dispatch:
  push:
    tags: 
    - v0.*
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.17'
        cache: 'yarn'
    - name: Install
      run: yarn install
    - name: Generate Icons
      run: yarn electron:generate-icons
    - name: Build
      run: yarn electron:build -mlw
    - name: deploy
      uses: "marvinpinto/action-automatic-releases@1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        files: |
          dist_electron/*.zip
          dist_electron/*.exe
          dist_electron/*.AppImage
          dist_electron/*.dmg
    
